language: ruby
rvm:
  - 2.3.1
env:
  - db_user=postgres db_password=
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database spa_backend_test;' -U postgres
script:
  - bundle exec rubocop -R
  - bundle exec rspec spec
